version: "3.9"

services:

  qdrant:
    image: qdrant/qdrant

    ports:
      - "6333:6333"

    volumes:
      - qdrant_storage:/qdrant/storage


  ollama:
    image: ollama/ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama


  backend:
    build: ./backend

    ports:
      - "8000:8000"

    depends_on:
      - qdrant
      - ollama

    volumes:
      - ./backend:/app

volumes:

  qdrant_storage:

  ollama_data: